export const CHARACTERS_GET = 'CHARACTERS_GET'
export const CHARACTERS_SET = 'CHARACTERS_SET'
export const CHARACTERS_LOADING = 'CHARACTERS_LOADING'
export const CHARACTERS_ERROR = 'CHARACTERS_ERROR'
